require:
  - "rubocop-minitest"
  - "rubocop-performance"
  - "rubocop-rake"

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/LineLength:
  Max: 120
  Exclude: 
    - "test/**/*.rb"

Metrics/BlockLength:
  Exclude: 
    - "test/**/*.rb"
    - "*.gemspec"
Metrics/ClassLength:
  Exclude: 
    - "test/**/*.rb"
Metrics/MethodLength:
  Exclude: 
    - "test/**/*.rb"

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/LambdaCall:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - vendor/**/*
